### ISSUE TITLE
Geting username and password

### ISSUE THREAD

**Issue by Dcdevcom** [norrisboat/MobileMoneySDK#2]
may you show us where to find mtn username and password is it availble for every one or not that for your Idea

**Comment by norrisboat** [comment]
@Dcdevcom You have to contact the merchant division of MTN and they will walk you through the process.

**Comment by Akwaboah** [comment]
So that username and password are just different from the normal merchant id

**Comment by norrisboat** [comment]
@Akwaboah  yes
